// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radigate.Server.Templates.Data;

#nullable disable

namespace Radigate.Server.Migrations.TemplatesData
{
    [DbContext(typeof(TemplatesDataContext))]
    [Migration("20230623144001_GroupPublicView")]
    partial class GroupPublicView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("GroupTemplatePatientTemplate", b =>
                {
                    b.Property<int>("GroupTemplatesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientTemplatesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupTemplatesId", "PatientTemplatesId");

                    b.HasIndex("PatientTemplatesId");

                    b.ToTable("GroupTemplatePatientTemplate");
                });

            modelBuilder.Entity("Radigate.Shared.Templates.GroupTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Public")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tasks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroupTemplates");
                });

            modelBuilder.Entity("Radigate.Shared.Templates.PatientTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PatientTemplates");
                });

            modelBuilder.Entity("GroupTemplatePatientTemplate", b =>
                {
                    b.HasOne("Radigate.Shared.Templates.GroupTemplate", null)
                        .WithMany()
                        .HasForeignKey("GroupTemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Radigate.Shared.Templates.PatientTemplate", null)
                        .WithMany()
                        .HasForeignKey("PatientTemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
