// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radigate.Server.Data;

#nullable disable

namespace Radigate.Server.Migrations
{
    [DbContext(typeof(PatientDataContext))]
    [Migration("20230606181548_PatientSeeding")]
    partial class PatientSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Radigate.Shared.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ryan",
                            LastName = "Stiles"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Greg",
                            LastName = "Proops"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Colin",
                            LastName = "Mocharie"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Wayne",
                            LastName = "Bradey"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Aishia",
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Clive",
                            LastName = "Owen"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Drew",
                            LastName = "Carey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
