// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radigate.Server.Data;

#nullable disable

namespace Radigate.Server.Migrations
{
    [DbContext(typeof(PatientDataContext))]
    [Migration("20230608152940_TaskSeeding")]
    partial class TaskSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Radigate.Shared.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ryan",
                            Identifier = "",
                            LastName = "Stiles"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Greg",
                            Identifier = "",
                            LastName = "Proops"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Colin",
                            Identifier = "",
                            LastName = "Mocharie"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Wayne",
                            Identifier = "",
                            LastName = "Bradey"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Aishia",
                            Identifier = "",
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Clive",
                            Identifier = "",
                            LastName = "Owen"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Drew",
                            Identifier = "",
                            LastName = "Carey"
                        });
                });

            modelBuilder.Entity("Radigate.Shared.TaskGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("TaskGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Standard",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "Physics Checks",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 3,
                            Label = "Standard",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 4,
                            Label = "Physics Checks",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 5,
                            Label = "Standard",
                            PatientId = 3
                        },
                        new
                        {
                            Id = 6,
                            Label = "Physics Checks",
                            PatientId = 3
                        },
                        new
                        {
                            Id = 7,
                            Label = "Standard",
                            PatientId = 4
                        },
                        new
                        {
                            Id = 8,
                            Label = "Physics Checks",
                            PatientId = 4
                        },
                        new
                        {
                            Id = 9,
                            Label = "Standard",
                            PatientId = 5
                        },
                        new
                        {
                            Id = 10,
                            Label = "Physics Checks",
                            PatientId = 5
                        },
                        new
                        {
                            Id = 11,
                            Label = "Standard",
                            PatientId = 6
                        },
                        new
                        {
                            Id = 12,
                            Label = "Physics Checks",
                            PatientId = 6
                        },
                        new
                        {
                            Id = 13,
                            Label = "Standard",
                            PatientId = 7
                        },
                        new
                        {
                            Id = 14,
                            Label = "Physics Checks",
                            PatientId = 7
                        });
                });

            modelBuilder.Entity("Radigate.Shared.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskGroupId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "",
                            Label = "Assigned RO",
                            TaskGroupId = 1,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 2,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 1,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 3,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 1,
                            Type = 2,
                            Value = "150.0"
                        },
                        new
                        {
                            Id = 4,
                            Comments = "",
                            Label = "Patient Status",
                            TaskGroupId = 1,
                            Type = 3,
                            Value = "2,Waiting,Assigned,Treating,Finished"
                        },
                        new
                        {
                            Id = 5,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 2,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 6,
                            Comments = "",
                            Label = "Assigned Physicist",
                            TaskGroupId = 2,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 7,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 2,
                            Type = 2,
                            Value = "12.55"
                        },
                        new
                        {
                            Id = 8,
                            Comments = "",
                            Label = "Assigned RO",
                            TaskGroupId = 3,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 9,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 3,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 10,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 3,
                            Type = 2,
                            Value = "150.0"
                        },
                        new
                        {
                            Id = 11,
                            Comments = "",
                            Label = "Patient Status",
                            TaskGroupId = 3,
                            Type = 3,
                            Value = "1,Waiting,Assigned,Treating,Finished"
                        },
                        new
                        {
                            Id = 12,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 4,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 13,
                            Comments = "",
                            Label = "Assigned Physicist",
                            TaskGroupId = 4,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 14,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 4,
                            Type = 2,
                            Value = "12.55"
                        },
                        new
                        {
                            Id = 15,
                            Comments = "",
                            Label = "Assigned RO",
                            TaskGroupId = 5,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 16,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 5,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 17,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 5,
                            Type = 2,
                            Value = "150.0"
                        },
                        new
                        {
                            Id = 18,
                            Comments = "",
                            Label = "Patient Status",
                            TaskGroupId = 5,
                            Type = 3,
                            Value = "1,Waiting,Assigned,Treating,Finished"
                        },
                        new
                        {
                            Id = 19,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 6,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 20,
                            Comments = "",
                            Label = "Assigned Physicist",
                            TaskGroupId = 6,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 21,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 6,
                            Type = 2,
                            Value = "12.55"
                        },
                        new
                        {
                            Id = 22,
                            Comments = "",
                            Label = "Assigned RO",
                            TaskGroupId = 7,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 23,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 7,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 24,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 7,
                            Type = 2,
                            Value = "150.0"
                        },
                        new
                        {
                            Id = 25,
                            Comments = "",
                            Label = "Patient Status",
                            TaskGroupId = 7,
                            Type = 3,
                            Value = "2,Waiting,Assigned,Treating,Finished"
                        },
                        new
                        {
                            Id = 26,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 8,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 27,
                            Comments = "",
                            Label = "Assigned Physicist",
                            TaskGroupId = 8,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 28,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 8,
                            Type = 2,
                            Value = "12.55"
                        },
                        new
                        {
                            Id = 29,
                            Comments = "",
                            Label = "Assigned RO",
                            TaskGroupId = 9,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 30,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 9,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 31,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 9,
                            Type = 2,
                            Value = "150.0"
                        },
                        new
                        {
                            Id = 32,
                            Comments = "",
                            Label = "Patient Status",
                            TaskGroupId = 9,
                            Type = 3,
                            Value = "3,Waiting,Assigned,Treating,Finished"
                        },
                        new
                        {
                            Id = 33,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 10,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 34,
                            Comments = "",
                            Label = "Assigned Physicist",
                            TaskGroupId = 10,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 35,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 10,
                            Type = 2,
                            Value = "12.55"
                        },
                        new
                        {
                            Id = 36,
                            Comments = "",
                            Label = "Assigned RO",
                            TaskGroupId = 11,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 37,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 11,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 38,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 11,
                            Type = 2,
                            Value = "150.0"
                        },
                        new
                        {
                            Id = 39,
                            Comments = "",
                            Label = "Patient Status",
                            TaskGroupId = 11,
                            Type = 3,
                            Value = "3,Waiting,Assigned,Treating,Finished"
                        },
                        new
                        {
                            Id = 40,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 12,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 41,
                            Comments = "",
                            Label = "Assigned Physicist",
                            TaskGroupId = 12,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 42,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 12,
                            Type = 2,
                            Value = "12.55"
                        },
                        new
                        {
                            Id = 43,
                            Comments = "",
                            Label = "Assigned RO",
                            TaskGroupId = 13,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 44,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 13,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 45,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 13,
                            Type = 2,
                            Value = "150.0"
                        },
                        new
                        {
                            Id = 46,
                            Comments = "",
                            Label = "Patient Status",
                            TaskGroupId = 13,
                            Type = 3,
                            Value = "2,Waiting,Assigned,Treating,Finished"
                        },
                        new
                        {
                            Id = 47,
                            Comments = "",
                            Label = "Approved by RO",
                            TaskGroupId = 14,
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 48,
                            Comments = "",
                            Label = "Assigned Physicist",
                            TaskGroupId = 14,
                            Type = 1,
                            Value = "No one"
                        },
                        new
                        {
                            Id = 49,
                            Comments = "",
                            Label = "Mass Volume",
                            TaskGroupId = 14,
                            Type = 2,
                            Value = "1.26"
                        });
                });

            modelBuilder.Entity("Radigate.Shared.TaskGroup", b =>
                {
                    b.HasOne("Radigate.Shared.Patient", "Patient")
                        .WithMany("TaskGroups")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Radigate.Shared.TaskItem", b =>
                {
                    b.HasOne("Radigate.Shared.TaskGroup", "TaskGroup")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskGroup");
                });

            modelBuilder.Entity("Radigate.Shared.Patient", b =>
                {
                    b.Navigation("TaskGroups");
                });

            modelBuilder.Entity("Radigate.Shared.TaskGroup", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
